{
  "private": true,
  "scripts": {
    "webpackStart": "webpack-dev-server --inline --hot",
    "webpackBuild": "webpack --display-error-details",
    "webpackWatch": "webpack --progress --colors --watch",
    "start": "roadhog server",
    "build": "roadhog build",
    "test": "roadhog test",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "engines": {
    "install-node": "6.9.2"
  },
  "dependencies": {
    "animate.css": "^3.5.2",
    "antd": "^2.6.3",
    "autoprefixer": "^6.7.5",
    "babel": "^6.23.0",
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.1",
    "babel-plugin-transform-object-assign": "^6.8.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-runtime": "^6.9.2",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "del": "^2.2.2",
    "dva": "^1.2.1",
    "dva-loading": "^0.2.0",
    "enhanced-resolve": "^3.1.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.10.0",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-htmlmin": "^3.0.0",
    "gulp-imagemin": "^3.1.1",
    "gulp-load-plugins": "^1.5.0",
    "gulp-ruby-sass": "^2.1.1",
    "gulp-size": "^2.1.0",
    "hammerjs": "^2.0.8",
    "imagemin-pngquant": "^5.0.0",
    "less-loader": "^2.2.3",
    "loader-runner": "^2.3.0",
    "path": "^0.12.7",
    "precss": "^1.4.0",
    "react": "^15.4.0",
    "react-dom": "^15.4.0",
    "request": "^2.79.0",
    "sass-loader": "^6.0.2",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.14.0",
    "webpack-dev-server": "^1.16.2",
    "webpack-visualizer-plugin": "^0.1.6",
    "wolfy87-eventemitter": "^5.1.0"
  },
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "cross-env": "^3.1.4",
    "got": "^6.7.1",
    "nyc": "^10.0.0",
    "postcss-pxtorem": "^3.3.1",
    "rimraf": "^2.5.4",
    "babel-eslint": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-import": "^1.1.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "expect": "^1.20.2",
    "husky": "^0.12.0",
    "redbox-react": "^1.3.2",
    "roadhog": "^0.5.2"
  }
}
